# Semantic Release Configuration
# ==============================

branches:
  - main
  - next
  - beta
  - name: "*.x"
    range: "*"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - publishCmd: "make sbom"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - pyproject.toml
        - control/cms/webapp/package.json
        - control/api/go.mod
        - edge/Cargo.toml
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/github"

preset: "angular"

releaseRules:
  - type: "feat"
    release: "minor"
  - type: "fix" 
    release: "patch"
  - type: "perf"
    release: "patch"
  - type: "docs"
    release: false
  - type: "style"
    release: false
  - type: "refactor"
    release: "patch"
  - type: "test"
    release: false
  - type: "build"
    release: "patch"
  - type: "ci"
    release: false
  - type: "chore"
    release: false
  - breaking: true
    release: "major"

parserOpts:
  noteKeywords:
    - BREAKING CHANGE
    - BREAKING CHANGES